### PR TITLE
Update walking and journaling

### LINKED ISSUE #282: Lengthen walking more and journalling to be more than 3 days
maybe 21?

### PR DESCRIPTION
**Pull request by jialin7878**
Fixes #282

### CODE REVIEW

**Comment by sebastiantoh** [comment]
i'm wondering if we should just delete the OG walking and journaling challenge, and create new ones instead, so we don't have to care about user tasks

**Comment by ianyong** [comment]
> i'm wondering if we should just delete the OG walking and journaling challenge, and create new ones instead, so we don't have to care about user tasks
> 
> (downside is that user data / progress will be lost, though i'm not sure if this is an actual problem...)

Yea, I agree with this.

**Comment by jialin7878** [comment]
Updated, hope it works as intended

**Review by ianyong — APPROVED** [review]
LGTM! Tested locally.

**Pull request merged**
