### PR TITLE
Display map for completed challenge

### LINKED ISSUE #189: Fix maps not being shown correctly for completed challenge bug

### PR DESCRIPTION
**Pull request by jialin7878**
Fixes #189

### CODE REVIEW

**Comment by sebastiantoh** [comment]
Getting this error
image

**Comment by jialin7878** [comment]
I'm confused :(

**Comment by jialin7878** [comment]
Fixed I think...

**Comment by jialin7878** [comment]
Noticing now that it has weird scrollbars, will fix

**Review by sebastiantoh — APPROVED** [review]
lgtm, ty!

snuck in a commit here: https://github.com/0dy553y/odyssey/pull/263/commits/263661f39992f18c28e9a50d5e46999bc2591971

**Pull request merged**
