### PR TITLE
Rework the 'current date' button & add snackbar as feedback

### LINKED ISSUE #279: Users might be confused when clicking on the 'current date' button

### PR DESCRIPTION
**Pull request by ianyong**
Fixes #279.

### CODE REVIEW

**Comment by ming-00** [comment]
Hmm this wouldn't show up on mobile right 🤔 
I was wondering if this would be a good alternative we can try? So instead of a permanent calendar button, the button only appears when scrolling to other dates
Screenshot 2021-11-07 at 6 05 34 PM

and if you scrolled forwards:
Screenshot 2021-11-07 at 6 07 03 PM

Would something like this work? I'm not sure about the placement though :')

**Comment by ianyong** [comment]
> Hmm this wouldn't show up on mobile right 🤔

It will!

> I was wondering if this would be a good alternative we can try? So instead of a permanent calendar button, the button only appears when scrolling to other dates Screenshot 2021-11-07 at 6 05 34 PM
> 
> and if you scrolled forwards: Screenshot 2021-11-07 at 6 07 03 PM
> 
> Would something like this work? I'm not sure about the placement though :')

Yea, I really like this idea (at least for the desktop view). How would it look on mobile though?

**Comment by ming-00** [comment]
> It will!

OH HAHA I read it as tooltip I'm sorry 🤦🏻‍♀️ 

Hmm I think we can also pull it off in mobile? Seems like most of the screens are wide enough to accommodate the button (maybe except galaxy fold but who ask them to get such a nonsense phone). Worst case the text can be split into two lines...?

**Comment by ianyong** [comment]
> Hmm I think we can also pull it off in mobile? Seems like most of the screens are wide enough to accommodate the button (maybe except galaxy fold but who ask them to get such a nonsense phone). Worst case the text can be split into two lines...?
> 
> Edit: nvm I tested it a bit and you're right... its a bit cluttered :/ do you think an arrow would suffice for mobile? @sebastiantoh @jialin7878 any other ideas :0 Screenshot 2021-11-07 at 11 23 01 PM

LOL "nonsense phone".

I think just the arrow looks fine, but then we come back to the root issue where it's not very clear what it does to the user. :/

**Comment by sebastiantoh** [comment]
maybe instead of an icon, we can be explicit and have it be a text button that says 'Today'? Not sure if it'll ruin the aesthetic tho haha

**Comment by ming-00** [comment]
Maybe not ideal but like this...?


> maybe instead of an icon, we can be explicit and have it be a text button that says 'Today'? Not sure if it'll ruin the aesthetic tho haha

Like this maybe?
Screenshot 2021-11-08 at 12 35 54 PM

**Comment by sebastiantoh** [comment]
> Maybe not ideal but like this...?
> 
> > maybe instead of an icon, we can be explicit and have it be a text button that says 'Today'? Not sure if it'll ruin the aesthetic tho haha
> 
> Like this maybe? Screenshot 2021-11-08 at 12 35 54 PM

Oh, I meant just replacing the calendar icon beside the bell icon with 'Today' lol

**Comment by ianyong** [comment]
> Like this maybe?
> Screenshot 2021-11-08 at 12 35 54 PM

This still breaks on perfectly acceptable widths. I've made use of just the arrow on mobile views, but with the snackbar.

**Review by sebastiantoh — APPROVED** [review]
lgtm!

**Pull request merged**
