### PR TITLE
Rename instances of 'badge' in code to 'memento'

### LINKED ISSUE #184: Mementos page path is still badges

### PR DESCRIPTION
**Pull request by ianyong**
Resolves #184.

### CODE REVIEW

**Comment by jialin7878** [comment]
iinw it's memento instead of momento

**Comment by ianyong** [comment]
> iinw it's memento instead of momento

OMG LOL, ok you saw nothing.

**Comment by jialin7878** [comment]
Merge conflicts, sorry!

**Review by sebastiantoh — APPROVED** [review]
lgtm!

**Pull request merged**
