### PR TITLE
Minor things

### PR DESCRIPTION
**Pull request by ming-00**
- Make challenge details page look more like mockup
 - Standardise join challenge & invite friends modal style (other prize related modals will be handled by jl)
 - Add obebebe to the home page no task message
 - Fix bug: the learn more about challenge link was clickable within the entire width of the page
 - Fix bug: add button hover turns white
 - Minor icon styling
 - Make category preview in explore page skinnier
 - Add snacc for task completion (bc I think the map can be confusing at first, wdyt?)

### CODE REVIEW

**Comment by jialin7878** [comment]
that's a lot of obebebe I see

**Review by sebastiantoh — APPROVED** [review]
looks good, ty!

**Comment by sebastiantoh** [comment]
ps there's still one more Forfeit challenge modal that has a different modal style. Feel free to merge this PR if jl will be handling that too?

**Comment by ming-00** [comment]
> ps there's still one more Forfeit challenge modal that has a different modal style. Feel free to merge this PR if jl will be handling that too?

Oh lemme go look at that! Tqtq

**Comment by sebastiantoh** [comment]
lgtm, ty!!

**Pull request merged**
