### PR TITLE
Jl/integrate map

### LINKED ISSUE #109: Character is not spawning on correct tile
hmm..it was working before

### PR DESCRIPTION
**Pull request by jialin7878**
The base functionality is kind of there.. but there are bugs

-- bugs (investigating)
= map dialog not in correct state

using this in rails console -- sign in as Squirtle
```

user_squirtle = User.create(username: 'Squirtle', display_name: 'Squirtle', password: 'password')
user_mario = User.create(username: 'Mario', display_name: 'Mario', password: 'password')
user_torchic = User.create(username: 'Torchic', display_name: 'Torchic', password: 'password')
user_luigi = User.create(username: 'Luigi', display_name: 'Luigi', password: 'password')


Friendship.create!(first_user_id: user_squirtle.id, second_user_id: user_mario.id)
Friendship.create!(first_user_id: user_squirtle.id, second_user_id: user_torchic.id)
Friendship.create!(first_user_id: user_squirtle.id, second_user_id: user_luigi.id)

user_challenge_walking = UserChallenge.new(user_id: user_squirtle.id, challenge_id: 1,
                                           started_at: 3.days.ago)
user_challenge_walking.schedule = Schedule.new(monday: true, tuesday: true, wednesday: true, thursday: true, friday: true, saturday: true, sunday: true)

user_challenge_walking.save!

UserTask.create!(user_id: user_squirtle.id, user_challenge_id: user_challenge_walking.id, task_id: 4,
                  completed_at: nil,
                  scheduled_for: 3.days.ago)


UserTask.create!(user_id: user_squirtle.id, user_challenge_id: user_challenge_walking.id, task_id: 5,
                  completed_at: nil,
                  scheduled_for: 2.days.ago)


UserTask.create!(user_id: user_squirtle.id, user_challenge_id: user_challenge_walking.id, task_id: 6,
                  completed_at: nil,
                  scheduled_for: 1.days.ago)

user_challenge_journalling = UserChallenge.new(user_id: user_squirtle.id, challenge_id: 2, started_at: 3.days.ago)
user_challenge_journalling.schedule = Schedule.new(monday: true, tuesday: true, wednesday: true, thursday: true, friday: true, saturday: true, sunday: true)

user_challenge_journalling.save!

UserTask.create!(user_id: user_squirtle.id, user_challenge_id: user_challenge_journalling.id, task_id: 1,
                  completed_at: nil,
                  scheduled_for: 3.days.ago)


UserTask.create!(user_id: user_squirtle.id, user_challenge_id: user_challenge_journalling.id, task_id: 2,
                  completed_at: nil,
                  scheduled_for: 2.days.ago)


UserTask.create!(user_id: user_squirtle.id, user_challenge_id: user_challenge_journalling.id, task_id: 3,
                  completed_at: nil,
                  scheduled_for: 1.days.ago)


user_challenge_walking = UserChallenge.new(user_id: user_mario.id, challenge_id: 1,
                                           started_at: 1.week.ago)
user_challenge_walking.schedule = Schedule.new(saturday: true, sunday: true)
user_challenge_walking.save!


UserTask.create!(user_id: user_mario.id, user_challenge_id: user_challenge_walking.id, task_id: 1,
                  completed_at: 1.days.ago,
                  scheduled_for: 1.days.ago)

user_challenge_walking = UserChallenge.new(user_id: user_torchic.id, challenge_id: 1,
                                           started_at: 1.week.ago)
user_challenge_walking.schedule = Schedule.new(saturday: true, sunday: true)
user_challenge_walking.save!

user_challenge_walking = UserChallenge.new(user_id: user_luigi.id, challenge_id: 1,
                                           started_at: 1.week.ago)
user_challenge_walking.schedule = Schedule.new(saturday: true, sunday: true)
user_challenge_walking.save!


```

fixes #109

### CODE REVIEW

**Comment by jialin7878** [comment]
The PR is getting a bit too big...maybe can review first :') -- the biggest bug rn is that when u check off task the Map cutscene isn't always in the correct state

**Review by sebastiantoh — APPROVED** [review]
looks good!

**Comment by sebastiantoh** [comment]
minor issue: Is it possible to set a limit on the amount that the user can zoom out?

image

**Comment by jialin7878** [comment]
> minor issue: Is it possible to set a limit on the amount that the user can zoom out?
> 

HAHA I did actually, not sure if it's not working or I still set too high, will look into it thankies

> Another minor issue:
> 
> * The map that opens after clicking on the map button in the Home page using a desktop doesn't fill up the entire screen (but when you check off a task, the map that opens does fill up the entire screen)

Ooh Ic will change

**Comment by sebastiantoh** [comment]
feel free to merge!

**Pull request merged**
