### PR TITLE
Map fixes

### PR DESCRIPTION
**Pull request by jialin7878**
Turns out part of the problem was my seed was wrong, did y'all encounter the bug while using the previous seed also? Or was it separate issue

updated:
```
user_squirtle = User.create(username: 'Squirtle', display_name: 'Squirtle', password: 'password')
user_mario = User.create(username: 'Mario', display_name: 'Mario', password: 'password')
user_torchic = User.create(username: 'Torchic', display_name: 'Torchic', password: 'password')
user_luigi = User.create(username: 'Luigi', display_name: 'Luigi', password: 'password')


Friendship.create!(first_user_id: user_squirtle.id, second_user_id: user_mario.id)
Friendship.create!(first_user_id: user_squirtle.id, second_user_id: user_torchic.id)
Friendship.create!(first_user_id: user_squirtle.id, second_user_id: user_luigi.id)

user_challenge_walking = UserChallenge.new(user_id: user_squirtle.id, challenge_id: 2,
                                           started_at: 3.days.ago)
user_challenge_walking.schedule = Schedule.new(monday: true, tuesday: true, wednesday: true, thursday: true, friday: true, saturday: true, sunday: true)

user_challenge_walking.save!

UserTask.create!(user_id: user_squirtle.id, user_challenge_id: user_challenge_walking.id, task_id: 4,
                  completed_at: nil,
                  scheduled_for: 3.days.ago)


UserTask.create!(user_id: user_squirtle.id, user_challenge_id: user_challenge_walking.id, task_id: 5,
                  completed_at: nil,
                  scheduled_for: 2.days.ago)


UserTask.create!(user_id: user_squirtle.id, user_challenge_id: user_challenge_walking.id, task_id: 6,
                  completed_at: nil,
                  scheduled_for: 1.days.ago)

user_challenge_journalling = UserChallenge.new(user_id: user_squirtle.id, challenge_id: 1, started_at: 3.days.ago)
user_challenge_journalling.schedule = Schedule.new(monday: true, tuesday: true, wednesday: true, thursday: true, friday: true, saturday: true, sunday: true)

user_challenge_journalling.save!

UserTask.create!(user_id: user_squirtle.id, user_challenge_id: user_challenge_journalling.id, task_id: 1,
                  completed_at: nil,
                  scheduled_for: 3.days.ago)


UserTask.create!(user_id: user_squirtle.id, user_challenge_id: user_challenge_journalling.id, task_id: 2,
                  completed_at: nil,
                  scheduled_for: 2.days.ago)


UserTask.create!(user_id: user_squirtle.id, user_challenge_id: user_challenge_journalling.id, task_id: 3,
                  completed_at: nil,
                  scheduled_for: 1.days.ago)


user_challenge_walking = UserChallenge.new(user_id: user_mario.id, challenge_id: 2,
                                           started_at: 1.week.ago)
user_challenge_walking.schedule = Schedule.new(saturday: true, sunday: true)
user_challenge_walking.save!


UserTask.create!(user_id: user_mario.id, user_challenge_id: user_challenge_walking.id, task_id: 1,
                  completed_at: 1.days.ago,
                  scheduled_for: 1.days.ago)

user_challenge_walking = UserChallenge.new(user_id: user_torchic.id, challenge_id: 1,
                                           started_at: 1.week.ago)
user_challenge_walking.schedule = Schedule.new(saturday: true, sunday: true)
user_challenge_walking.save!

user_challenge_walking = UserChallenge.new(user_id: user_luigi.id, challenge_id: 1,
                                           started_at: 1.week.ago)
user_challenge_walking.schedule = Schedule.new(saturday: true, sunday: true)
user_challenge_walking.save!
```

### CODE REVIEW

**Comment by sebastiantoh** [comment]
https://user-images.githubusercontent.com/24363622/139605796-baa89dd7-8115-4dec-8657-7e6479fcc568.mp4

This isn't really caused by this PR, but clicking on the map button in the task card opens up the wrong map

**Comment by sebastiantoh** [comment]
Am I supposed to see other people on the map when I log in as squirtle?

**Comment by jialin7878** [comment]
> Clicking on the map button in the task card of a completed challenge opens up the wrong map.
> 
> It's because the challenge is completed, and the map data aren't fetched for completed challenges (is this intentional?). Previously, tasks for completed challenges won't appear in the list anymore, but I think this is wrong because people might misclick so I modified it here [ba18422](https://github.com/0dy553y/odyssey/commit/ba18422cff6ac50addb5988915a2fc901c0e3690)
> 
> (low priority though, since I don't think challenges will be completed that soon)

I see...I think we can maybe disable the map button on completed challenges because
 - clicking on map button brings user to their map now instead of map at that point of time (maybe the UI doesn't reflect this very well hmm) so it shouldn't show completed challenges in the past
 - showing completed challenges in carousel increases number of swipes for users to get to ongoing map(?)
 
I think having a 15 seconds undo snackbar then disabling them from toggling the cards after that might be better for misclicks (?)

**Comment by sebastiantoh** [comment]
> I think having a 15 seconds undo snackbar then disabling them from toggling the cards after that might be better for misclicks (?)

hmm, in that case, should the completed task still appear in the carousel once it's checked off?

**Comment by jialin7878** [comment]
> Am I supposed to see other people on the map when I log in as squirtle?
> 
> (p.s. I think your seed is still wrong since the number of user tasks isn't correct for some users. Not sure if it matters tho)

regression, thanks for spotting ! shld see mario walking with u and torchic and luigi being grateful with u

**Comment by jialin7878** [comment]
> > I think having a 15 seconds undo snackbar then disabling them from toggling the cards after that might be better for misclicks (?)
> 
> hmm, in that case, should the completed task still appear in the carousel once it's checked off?

i'll do the either disable map button or showing completed challenge in diff route thing maybe tmr since there's abit more time~

**Review by sebastiantoh — APPROVED** [review]
lgtm ty!

**Pull request merged**
