### PR TITLE
Tweaks and issues

### LINKED ISSUE #197: Standardise styling for modals
join challenge, invite friends, view prize modals etc are all different looking

### PR DESCRIPTION
**Pull request by ming-00**
Ohoy

Desktop view looks amazing 😻 
 - Fix searchbar in explore page, input base was tiny and not filling the box
 - Fix flat safari (?!?!?!)
 - Add option to open map from challenge details page (#213)
 - Minor styling of desktop view for category, challenge details page and a bit of profile page
 - Style the post modal (idt there are any more?) (should close #197)
 - Add success message on post
 - Implement tab of most popular challenges (rn it's just picking the top 3 most enrolled past and present total count... feel free to suggest a better metric!) (#190)

More tings
 - #267 
 - Style profile buttons for accept/ reject friend req
 - Format post items a bit, add link on user name click

### CODE REVIEW

**Comment by sebastiantoh** [comment]
hmm, for the pancake, i get this on mobile

image

**Comment by sebastiantoh** [comment]
Search bar on mobile is getting cut off too 

image

**Comment by ming-00** [comment]
Screenshot 2021-11-06 at 11 53 39 PM

lies... another day another disappointment

**Comment by ming-00** [comment]
https://user-images.githubusercontent.com/59130765/140616724-f9eb9245-af77-44a5-978a-aff1936c1c3e.mov

Finally found a media query that seems to only work on Safari? Pushing daisies at this point

**Comment by jialin7878** [comment]
Remove friend modal

**Review by sebastiantoh — APPROVED** [review]
lgtm, ty!

**Pull request merged**
